//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReservationManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bdd.
        /// </summary>
        public static string Bdd {
            get {
                return ResourceManager.GetString("Bdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bdd :.
        /// </summary>
        public static string Bdd_Field {
            get {
                return ResourceManager.GetString("Bdd_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category :.
        /// </summary>
        public static string Category_Field {
            get {
                return ResourceManager.GetString("Category_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Places :.
        /// </summary>
        public static string CategoryPlaces_Field {
            get {
                return ResourceManager.GetString("CategoryPlaces_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Prices € :.
        /// </summary>
        public static string CategoryPrices_Field {
            get {
                return ResourceManager.GetString("CategoryPrices_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client :.
        /// </summary>
        public static string Client_Field {
            get {
                return ResourceManager.GetString("Client_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        public static string Date_Field {
            get {
                return ResourceManager.GetString("Date_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete some reservations !.
        /// </summary>
        public static string DeleteReservations {
            get {
                return ResourceManager.GetString("DeleteReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        public static string Description_Field {
            get {
                return ResourceManager.GetString("Description_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist.
        /// </summary>
        public static string Error_DoesNotExist {
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length must be &gt;= 3.
        /// </summary>
        public static string Error_LengthGreaterEqual3 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must match confirm password.
        /// </summary>
        public static string Error_MustMatchConfirmPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must match password.
        /// </summary>
        public static string Error_MustMatchPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        public static string Error_NotAvailable {
            get {
                return ResourceManager.GetString("Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong password.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name :.
        /// </summary>
        public static string FirstName_Field {
            get {
                return ResourceManager.GetString("FirstName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Places.
        /// </summary>
        public static string FreePlaces {
            get {
                return ResourceManager.GetString("FreePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has.
        /// </summary>
        public static string Has {
            get {
                return ResourceManager.GetString("Has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reservations !!!.
        /// </summary>
        public static string HasReservations {
            get {
                return ResourceManager.GetString("HasReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name :.
        /// </summary>
        public static string LastName_Field {
            get {
                return ResourceManager.GetString("LastName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don´t have a login and a password, click.
        /// </summary>
        public static string LoginView_Message_1 {
            get {
                return ResourceManager.GetString("LoginView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string LoginView_Message_2 {
            get {
                return ResourceManager.GetString("LoginView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to sign-up..
        /// </summary>
        public static string LoginView_Message_3 {
            get {
                return ResourceManager.GetString("LoginView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudo :.
        /// </summary>
        public static string LoginView_Pseudo {
            get {
                return ResourceManager.GetString("LoginView_Pseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand Box.
        /// </summary>
        public static string Menu_SandBox {
            get {
                return ResourceManager.GetString("Menu_SandBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing DataGrid.
        /// </summary>
        public static string Menu_SandBox_DataGrid {
            get {
                return ResourceManager.GetString("Menu_SandBox_DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Master / Detail.
        /// </summary>
        public static string Menu_SandBox_MasterDetail {
            get {
                return ResourceManager.GetString("Menu_SandBox_MasterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string Name_Field {
            get {
                return ResourceManager.GetString("Name_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New reservation.
        /// </summary>
        public static string New_reservation {
            get {
                return ResourceManager.GetString("New_reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Show.
        /// </summary>
        public static string NewShow {
            get {
                return ResourceManager.GetString("NewShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no places availible for this show !.
        /// </summary>
        public static string NoPlaces {
            get {
                return ResourceManager.GetString("NoPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reservations.
        /// </summary>
        public static string NoReservations {
            get {
                return ResourceManager.GetString("NoReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Possible.
        /// </summary>
        public static string NotPossible {
            get {
                return ResourceManager.GetString("NotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number :.
        /// </summary>
        public static string Number_Field {
            get {
                return ResourceManager.GetString("Number_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code :.
        /// </summary>
        public static string PostalCode_Field {
            get {
                return ResourceManager.GetString("PostalCode_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices €.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show :.
        /// </summary>
        public static string Show_Field {
            get {
                return ResourceManager.GetString("Show_Field", resourceCulture);
            }
        }
    }
}
