//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int numS { get; set; }
        public int numC { get; set; }
        public int numCat { get; set; }
        public int nbr { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Client Client { get; set; }
        public virtual Show Show { get; set; }
    }
}
