//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idU { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
    }
}
